name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Restore Gradle Cache
      uses: actions/cache/restore@v4
      with:
          path: |
            ~/.android/build-cache
            ~/.android/cache
          key: android-${{ github.run_id }}
          restore-keys: android-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Download Dependencies
      run: ./gradlew androidDependencies

    - name: Save Gradle Cache
      uses: actions/cache/save@v4
      with:
          path: |
            ~/.android/build-cache
            ~/.android/cache
          key: android-${{ github.run_id }}
          restore-keys: android-
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew lint test
